-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 10:14:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HotelReservation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HotelReservation` ;

-- -----------------------------------------------------
-- Schema HotelReservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelReservation` ;
USE `HotelReservation` ;

-- -----------------------------------------------------
-- Table `HotelReservation`.`Amenity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Amenity` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Amenity` (
  `AmenityID` SMALLINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AmenityName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AmenityID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Customer` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Customer` (
  `CustomerID` BIGINT(20) UNSIGNED NOT NULL,
  `Firstname` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(60) NULL DEFAULT NULL,
  `Employee_EmployeeID` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`),
  INDEX (`Employee_EmployeeID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Employee_EmployeeID`)
    REFERENCES `HotelReservation`.`Employee` (`EmployeeID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Employee` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Employee` (
  `EmployeeID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Postition` VARCHAR(45) NOT NULL,
  `Start_time` TIME NOT NULL,
  `End_time` TIME NOT NULL,
  PRIMARY KEY (`EmployeeID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Hotel` (
  `HotelID` MEDIUMINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`HotelID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`HotelEmployee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`HotelEmployee` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`HotelEmployee` (
  `Hotel_HotelID` MEDIUMINT(10) UNSIGNED NOT NULL,
  `Employee_EmployeeID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`Hotel_HotelID`, `Employee_EmployeeID`),
  INDEX (`Employee_EmployeeID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Hotel_HotelID`)
    REFERENCES `HotelReservation`.`Hotel` (`HotelID`),
  CONSTRAINT ``
    FOREIGN KEY (`Employee_EmployeeID`)
    REFERENCES `HotelReservation`.`Employee` (`EmployeeID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Reservation` (
  `ReservationID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Customer_CustomerID` BIGINT(20) UNSIGNED NOT NULL,
  `Total` DECIMAL(12,2) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`ReservationID`),
  INDEX (`Customer_CustomerID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `HotelReservation`.`Customer` (`CustomerID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`ReservationDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`ReservationDetail` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`ReservationDetail` (
  `ReservationDetailID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Reservation_ReservationID` BIGINT(20) UNSIGNED NOT NULL,
  `RoomReservation_RoomReservationID` BIGINT(20) UNSIGNED NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `Rate` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`ReservationDetailID`),
  INDEX (`Reservation_ReservationID` ASC) VISIBLE,
  INDEX (`RoomReservation_RoomReservationID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Reservation_ReservationID`)
    REFERENCES `HotelReservation`.`Reservation` (`ReservationID`),
  CONSTRAINT ``
    FOREIGN KEY (`RoomReservation_RoomReservationID`)
    REFERENCES `HotelReservation`.`RoomReservation` (`RoomReservationID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Room` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Room` (
  `RoomID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `RoomNumber` SMALLINT(10) UNSIGNED NOT NULL,
  `RoomType_RoomTypeID` SMALLINT(10) UNSIGNED NOT NULL,
  `Hotel_HotelID` MEDIUMINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`RoomID`),
  INDEX (`RoomType_RoomTypeID` ASC) VISIBLE,
  INDEX (`Hotel_HotelID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`RoomType_RoomTypeID`)
    REFERENCES `HotelReservation`.`RoomType` (`RoomTypeID`),
  CONSTRAINT ``
    FOREIGN KEY (`Hotel_HotelID`)
    REFERENCES `HotelReservation`.`Hotel` (`HotelID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomAmenity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomAmenity` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomAmenity` (
  `Room_RoomID` INT(10) UNSIGNED NOT NULL,
  `Amenity_AmenityID` SMALLINT(10) UNSIGNED NOT NULL,
  `AmenityQuantity` TINYINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`Room_RoomID`, `Amenity_AmenityID`),
  INDEX (`Amenity_AmenityID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Room_RoomID`)
    REFERENCES `HotelReservation`.`Room` (`RoomID`),
  CONSTRAINT ``
    FOREIGN KEY (`Amenity_AmenityID`)
    REFERENCES `HotelReservation`.`Amenity` (`AmenityID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomRate` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomRate` (
  `RoomRateID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Rate` DECIMAL(12,2) UNSIGNED NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `RoomType_RoomTypeID` SMALLINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`RoomRateID`),
  INDEX (`RoomType_RoomTypeID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`RoomType_RoomTypeID`)
    REFERENCES `HotelReservation`.`RoomType` (`RoomTypeID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomReservation` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomReservation` (
  `RoomReservationID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Room_RoomID` INT(10) UNSIGNED NOT NULL,
  `Reservation_ReservationID` BIGINT(20) UNSIGNED NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`RoomReservationID`),
  INDEX (`Room_RoomID` ASC) VISIBLE,
  INDEX (`Reservation_ReservationID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Room_RoomID`)
    REFERENCES `HotelReservation`.`Room` (`RoomID`),
  CONSTRAINT ``
    FOREIGN KEY (`Reservation_ReservationID`)
    REFERENCES `HotelReservation`.`Reservation` (`ReservationID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomReservationCustomer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomReservationCustomer` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomReservationCustomer` (
  `Customer_CustomerID` BIGINT(20) UNSIGNED NOT NULL,
  `RoomReservation_RoomReservationID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`Customer_CustomerID`, `RoomReservation_RoomReservationID`),
  INDEX (`RoomReservation_RoomReservationID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `HotelReservation`.`Customer` (`CustomerID`),
  CONSTRAINT ``
    FOREIGN KEY (`RoomReservation_RoomReservationID`)
    REFERENCES `HotelReservation`.`RoomReservation` (`RoomReservationID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomType` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomType` (
  `RoomTypeID` SMALLINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `RoomType` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`RoomTypeID`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
