-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 14:41:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HotelReservation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HotelReservation` ;

-- -----------------------------------------------------
-- Schema HotelReservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelReservation` ;
USE `HotelReservation` ;

-- -----------------------------------------------------
-- Table `HotelReservation`.`Amenity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Amenity` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Amenity` (
  `AmenityID` INT UNSIGNED NOT NULL,
  `AmenityName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AmenityID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Customer` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Customer` (
  `CustomerID` INT UNSIGNED NOT NULL,
  `Firstname` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(60) NULL DEFAULT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `RoomRating_RoomRatingID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CustomerID`),
  CONSTRAINT `fk_Customer_RoomRating`
    FOREIGN KEY (`RoomRating_RoomRatingID`)
    REFERENCES `HotelReservation`.`RoomRating` (`RoomRatingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `HotelReservation`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Employee` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Employee` (
  `EmployeeID` INT UNSIGNED NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Postition` VARCHAR(45) NOT NULL,
  `Start_time` TIME NOT NULL,
  `End_time` TIME NOT NULL,
  `Hotel_HotelID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EmployeeID`, `Hotel_HotelID`),
  CONSTRAINT `fk_Hotel_HotelID1`
    FOREIGN KEY (`Hotel_HotelID`)
    REFERENCES `HotelReservation`.`Hotel` (`HotelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `HotelReservation`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Hotel` (
  `HotelID` INT UNSIGNED NOT NULL,
  `HotelName` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`HotelID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`Room` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`Room` (
  `RoomID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `RoomNumber` SMALLINT(10) UNSIGNED NOT NULL,
  `RoomType_RoomTypeID` INT UNSIGNED NOT NULL,
  `Hotel_HotelID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RoomID`),
  CONSTRAINT `fk_RoomType_RoomTypeID`
    FOREIGN KEY (`RoomType_RoomTypeID`)
    REFERENCES `HotelReservation`.`RoomType` (`RoomTypeID`),
  CONSTRAINT `fk_Hotel_HotelID2`
    FOREIGN KEY (`Hotel_HotelID`)
    REFERENCES `HotelReservation`.`Hotel` (`HotelID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomAmenity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomAmenity` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomAmenity` (
  `Room_RoomID` INT(10) UNSIGNED NOT NULL,
  `Amenity_AmenityID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Room_RoomID`, `Amenity_AmenityID`),
  CONSTRAINT `fk_Room_RoomID1`
    FOREIGN KEY (`Room_RoomID`)
    REFERENCES `HotelReservation`.`Room` (`RoomID`),
  CONSTRAINT `fk_Amenity_AmenityID`
    FOREIGN KEY (`Amenity_AmenityID`)
    REFERENCES `HotelReservation`.`Amenity` (`AmenityID`));


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomRating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomRating` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomRating` (
  `RoomRatingID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Rate` DECIMAL(12,2) UNSIGNED NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `Room_RoomID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`RoomRatingID`),
  CONSTRAINT `fk_Room_RoomID2`
    FOREIGN KEY (`Room_RoomID`)
    REFERENCES `HotelReservation`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomReservation` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomReservation` (
  `RoomReservationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Room_RoomID` INT UNSIGNED NOT NULL,
  `Reservation_ReservationID` INT UNSIGNED NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `Total` DECIMAL(12,2) NULL,
  `Customer_CustomerID` INT UNSIGNED NOT NULL,
  `ReservationDetails` VARCHAR(255) NULL,
  PRIMARY KEY (`RoomReservationID`),
  CONSTRAINT `fk_Room_RoomID`
    FOREIGN KEY (`Room_RoomID`)
    REFERENCES `HotelReservation`.`Room` (`RoomID`),
  CONSTRAINT `fk_Customer_CustomerID`
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `HotelReservation`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `HotelReservation`.`RoomType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservation`.`RoomType` ;

CREATE TABLE IF NOT EXISTS `HotelReservation`.`RoomType` (
  `RoomTypeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RoomType` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`RoomTypeID`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
