import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'jsonprint'
})
export class JsonPrint implements PipeTransform {

  transform(value: any, ...args): any {
    return JSON.stringify(value, null, 2)
      .replace('room_hotelId', 'Hotel info')
      .replace('hotelName', 'hotel name')
      .replace('roomID', 'Room id')
      .replace('roomNumber', 'Room number')
      .replace('room_roomtype', 'Room info')
      .replace('roomType', 'room type')
      .replace('roomTypeID', 'room type id')
      .replace('availability', 'Available')
      .replace('180', '180 $')
      .replace('60', '60 $')
      .replace('120', '120 $')
      .replace('300', '300 $')
      .replace('{', '')
      .replace('{', '')
      .replace('}', '')
      .replace(',', '')
      .replace(',', '')
      .replace(',', '')
      .replace(',', '')
      .replace(',', '')
      .replace(',', '')
      .replace(',', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('{', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('"', '')
      .replace('}', '')
      .replace('}', '');
  }
}
